---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: firstdeployment
    labels:
       app: zomato
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
       labels:
         app: zomato
    spec:
      containers:
         - name: cont-1
           image: shaikmustafa/dm
           ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zomatoservice
spec:
  selector:
    app: zomato
  ports:
     - port: 80
       targetPort: 80
       nodePort: 30002
  type: NodePort
