---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: emptydirdeployment
   labels:
      app: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
        labels:
          app: swiggy
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volumefored
              mountPath: "/etc/config"
      volumes:
          PersistentVolumeClaim:
          name: mypvc
