---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 10Gi
  accessModes:
     - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0268ef5bbe767a6aa
    fsType: ext
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: emptydirdeployment
   labels:
      app: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
        labels:
          app: swiggy
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volumefored
              mountPath: "/etc/config"
      volumes:
      - name: volumefored
        PersistentVolumeClaim:
          claimName: mypvc
